phrase:
  access_token: 4a9878df7578c59204f11ff1b8dc6192f2e90ee98aa957a5f519d977771f1eb3
  project_id: 3654ebe6da21c1c8808c12de4bd50ada
  push:
    sources:
    - file: ./en.json
      params:
        file_format: json
  pull:
    targets:
    - file: ./en.json
      params:
        file_format: json
